name: build-and-test

on:
  push:
  pull_request:
  merge_group:

jobs:
  build-kernel:
    runs-on: ${{ github.repository_owner == 'sched-ext' && fromJSON('[ "self-hosted", "linux", "x64" ]') || 'ubuntu-latest' }}
    steps:
      - name: Install Nix
        if: ${{ runner.environment == 'github-hosted' }}
        uses: DeterminateSystems/nix-installer-action@main

      - uses: actions/checkout@v4

      - uses: ./.github/actions/build-kernel
        with:
          repo-name: sched_ext/for-next

  build-kernel-legacy:
    uses: ./.github/workflows/build-kernel.yml
    with:
      repo-name: sched_ext/for-next

  rust-tests:
    runs-on: ${{ github.repository_owner == 'sched-ext' && fromJSON('[ "self-hosted", "linux", "x64" ]') || 'ubuntu-latest' }}
    needs:
      - build-kernel
      - build-kernel-legacy
    steps:
      - name: Install Nix
        if: ${{ runner.environment == 'github-hosted' }}
        uses: DeterminateSystems/nix-installer-action@main

      - uses: actions/checkout@v4

      - name: Load dependencies
        run: nix run ./.github/include#nix-develop-gha -- ./.github/include#restore-kernels

      - uses: ./.github/actions/build-kernel
        with:
          repo-name: sched_ext/for-next

      - name: Format
        run: nix run ./.github/include#ci -- format

      - name: Build
        run: nix run ./.github/include#ci -- build

      - name: Clippy
        run: nix run ./.github/include#ci -- clippy

      - name: Test
        run: nix run ./.github/include#ci -- test

  integration-test:
    uses: ./.github/workflows/integration-tests.yml
    needs:
      - build-kernel
      - build-kernel-legacy
    with:
      repo-name: sched_ext/for-next

  pages:
    runs-on: ubuntu-24.04
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write  # To push a branch
      pages: write  # To push to a GitHub Pages site
      id-token: write # To update the deployment status
    steps:
      # prevent cache permission errors
      - run: sudo chown root /usr/bin/tar && sudo chmod u+s /usr/bin/tar
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/install-deps-action
      - name: Build Book and Linux Docs
        run: |
          cd / && rustup component add rustfmt && cd $OLDPWD
          RUSTDOCFLAGS="--enable-index-page -Zunstable-options" cargo +nightly doc --workspace --no-deps --bins --lib --examples --document-private-items
          sudo apt install build-essential graphviz sphinx-doc python3-sphinx-rtd-theme texlive-latex-recommended python3-yaml -y
          cargo install htmlq
          git clone --single-branch -b for-next --depth 1 https://git.kernel.org/pub/scm/linux/kernel/git/tj/sched_ext.git linux
          cd linux
          make DOCS_THEME=sphinx_rtd_theme SPHINXDIRS=scheduler htmldocs
          make DOCS_THEME=sphinx_rtd_theme SPHINXDIRS=bpf htmldocs
          cd ..
          cp -a linux/Documentation/output/scheduler target/doc/
          cp -a linux/Documentation/output/bpf target/doc/
          sed -i 's%<li><a href="server/index.html">server</a></li>%<li><a href="server/index.html">server</a></li><li><a href="scheduler/sched-ext.html">Kernel Sched Ext Docs</a></li><li><a href="bpf/helpers.html">Kernel Bpf Helpers Docs</a></li>%' target/doc/index.html
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'target/doc'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
